DemoMVC/Controllers/DateController.cs
using DemoMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoMVC.Controllers
{
    
    public class DateController : Controller
    {
        // GET: Date
        static List<EMPDATA> l=null;
        public ActionResult DateView()
        {
            return View();
        }
        public ActionResult extractdate()
        {

            DateTime start = DateTime.Parse(Request.Form["txtsd"]);
            DateTime end = DateTime.Parse(Request.Form["txted"]);
           l= DBoperations.Empdate(start, end);
            ViewBag.list = l;

            return View("DateView");
        }




    }
}

DemoMVC/Views/Date/DateView.cshtml
@model IEnumerable<DemoMVC.Models.EMPDATA>
@{
    ViewBag.Title = "DateView";
}

<h2>DateView</h2>
@using(Html.BeginForm("extractdate","Date"))
{
    <table>
        <tr>
            <td>Start Date</td>
            <td>@Html.TextBox("txtsd")</td>
        </tr>
        <tr>
            <td>End Date</td>
            <td>@Html.TextBox("txted")</td>
        </tr>
        <tr>
            <td><input type="submit" value="Submit" /></td>
        </tr>
    </table>
    if(ViewBag.list!=null)
    {
<table>
    <tr>
        <td>EMPNO</td>
        <td>ENAME</td>
        <td>JOB</td>
        <td>MGR</td>
        <td>HIREDATE</td>
        <td>SAL</td>
        <td>COMM</td>
        <td>DEPTNO</td>

    </tr>
    @foreach(var i in ViewBag.list)
    {


<tr>
    <td>@i.EMPNO</td>
    <td>@i.ENAME</td>
    <td>@i.JOB</td>
    <td>@i.MGR</td>
    <td>@i.HIREDATE</td>
    <td>@i.SAL</td>
    <td>@i.COMM</td>
    <td>@i.DEPTNO</td>

</tr>

    }

</table>
        }

    }