DemoMVC/Controllers/Radio2Controller.cs
using DemoMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoMVC.Controllers
{
    public class Radio2Controller : Controller
    {
        // GET: Radio2
        List<EMPDATA> l = null;
        public ActionResult Index1()
        {
          l=  DBoperations.emptable();

            ViewBag.emplist = l;

           return View();
        }
        public ActionResult radioextract()
        {
            //l = DBoperations.emptable();
            int empno = Convert.ToInt32(Request.Form["rdb"]);

                       

            return View(DBoperations.empemp(empno));

        }
    }
}

DemoMVC/Views/Radio2/Index1.cshtml
@{
    ViewBag.Title = "Index1";
}

<h2>Index1</h2>
@using(Html.BeginForm("radioextract","Radio2"))
{
<table>
    <tr>
        <td>EMPNO</td>
        <td>ENAME</td>
        <td>JOB</td>
        <td>MGR</td>
        <td>HIREDATE</td>
        <td>SAL</td>
        <td>COMM</td>
        <td>DEPTNO</td>
        <td><input type="submit" value="submit" /></td>
    </tr>

    @foreach (var i in ViewBag.emplist as IList<DemoMVC.Models.EMPDATA>)
    {
        <tr>
            <td>@Html.RadioButton("rdb", i.EMPNO)</td>
            <td>@i.EMPNO</td>
            <td>@i.ENAME</td>
            <td>@i.JOB</td>
            <td>@i.MGR</td>
            <td>@i.HIREDATE</td>
            <td>@i.SAL</td>
            <td>@i.COMM</td>
            <td>@i.DEPTNO</td>

        </tr>

    }


</table>



}

DemoMVC/Views/Radio2/radioextract.cshtml
@model DemoMVC.Models.EMPDATA
@{
    ViewBag.Title = "radioextract";
}

<h2>radioextract</h2>
@using(Html.BeginForm())
{
    if (Model!= null)
    {
<table>
    <tr>
        <td>Empno</td>
        <td>@Html.TextBoxFor(a => a.EMPNO)</td>
    </tr>
    <tr>
        <td>Ename</td>
        <td>@Html.TextBoxFor(a => a.ENAME)</td>
    </tr>
    <tr>
        <td>Job</td>
        <td>@Html.TextBoxFor(a => a.JOB)</td>
    </tr>
    <tr>
        <td>MGR</td>
        <td>@Html.TextBoxFor(a => a.MGR)</td>
    </tr>
    <tr>
        <td>Hiredate</td>
        <td>@Html.TextBoxFor(a => a.HIREDATE)</td>
    </tr>
    <tr>
        <td>SAL</td>
        <td>@Html.TextBoxFor(a => a.SAL)</td>
    </tr>
    <tr>
        <td>Comm</td>
        <td>@Html.TextBoxFor(a => a.COMM)</td>
    </tr>
    <tr>
        <td>deptno</td>
        <td>@Html.TextBoxFor(a => a.DEPTNO)</td>
    </tr>


    







</table>


    }


}