DemoMVC/Controllers/BoundController.cs
using DemoMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoMVC.Controllers
{
    public class BoundController : Controller
    {
        // GET: Bound
        public ActionResult Index()
        {


            Emp e = new Emp();
            return View(e);
        }
        public ActionResult display(Emp A)
        {



            return View(A);
        }
        public ActionResult Index1()
        {


            Emp e = new Emp();
            return View(e);
        }
        [HttpPost]
        public ActionResult Index1(Emp a)
        {
            return View("Display",a);
        }
        public ActionResult Unbound()
        {
            return View();

        }
        public ActionResult showdata()
        {
            Emp e = new Emp();
            e.Empno = int.Parse(Request.Form["txtempno"]);
            e.Ename = Request.Form["txtename"];
            e.Sal = double.Parse(Request.Form["txtsal"]);
            return View(e);
        }
    }
}

DemoMVC/Views/Bound/Index.cshtml
@model DemoMVC.Models.Emp
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using(Html.BeginForm("Display","Bound"))
{
    <table>
        <tr>
            <td>Empno</td>
            <td>@Html.TextBoxFor(a=>a.Empno)</td>
        </tr>
        <tr>
            <td>Ename</td>
            <td>@Html.TextBoxFor(a=>a.Ename)</td>
        </tr>
        <tr>
            <td>Salary</td>
            <td>@Html.TextBoxFor(a=>a.Sal)</td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Submit" />
            </td>
        </tr>


    </table>





}

DemoMVC/Views/Bound/Index1.cshtml
@model DemoMVC.Models.Emp
@{
    ViewBag.Title = "Index1";
}

<h2>Index1</h2>
@using(Html.BeginForm())
{
<table>
    <tr>
        <td>@Html.TextBoxFor(a => a.Empno)</td>
    </tr>
    <tr><td>@Html.TextBoxFor(a => a.Ename)</td></tr>
    <tr><td>@Html.TextBoxFor(a => a.Sal)</td></tr>
    <tr>
        <td>
            <input type="submit" value="Submit" />
        </td>
    </tr>

</table>
}

DemoMVC/Views/Bound/Unbound.cshtml
@{
    ViewBag.Title = "Unbound";
}

<h2>Unbound</h2>
@using(Html.BeginForm("showdata","Bound"))
{
<table>
    <tr>
        <td>Empno</td>
        <td>@Html.TextBox("txtempno")</td>
    </tr>
    <tr>
        <td>Ename</td>
        <td>@Html.TextBox("txtename")</td>
    </tr>
    <tr>
        <td>Salary</td>
        <td>@Html.TextBox("txtsal")</td>
    </tr>
<tr>
    <td>
        <input type="submit" />
    </td>
</tr>

</table>
}

DemoMVC/Views/Bound/display.cshtml
@model DemoMVC.Models.Emp
@{
    ViewBag.Title = "display";
}

<h2>display</h2>
Empno:@Model.Empno
Ename:@Model.Ename
Salary:@Model.Sal

DemoMVC/Views/Bound/showdata.cshtml
@model DemoMVC.Models.Emp
@{
    ViewBag.Title = "showdata";
}

<h2>showdata</h2>
Empno: @Model.Empno
Ename: @Model.Ename
Salary: @Model.Sal